BEGIN;

-- ============================================================
-- KSS ERP: Driver Settlement Document Architecture
--
-- Creates an immutable settlement document and line-level
-- historical snapshot for completed driver trips and direct
-- driver advances.
--
-- POD is intentionally NOT part of settlement eligibility.
-- ============================================================


-- ============================================================
-- 1. SETTLEMENT HEADER
-- ============================================================

CREATE SEQUENCE IF NOT EXISTS public.driver_settlement_number_seq
  AS bigint
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1;


CREATE TABLE IF NOT EXISTS public.driver_settlement_batches (
  settlement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  settlement_number text NOT NULL UNIQUE,

  driver_id integer NOT NULL
    REFERENCES public.drivers(driver_id),

  from_date date NOT NULL,
  to_date date NOT NULL,

  trip_count integer NOT NULL DEFAULT 0,
  advance_count integer NOT NULL DEFAULT 0,

  driver_bata numeric NOT NULL DEFAULT 0,
  halt_bata numeric NOT NULL DEFAULT 0,
  trip_cash_advance numeric NOT NULL DEFAULT 0,
  direct_advance numeric NOT NULL DEFAULT 0,

  net_balance numeric NOT NULL DEFAULT 0,

  settlement_status text NOT NULL DEFAULT 'SETTLED',

  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by text NULL,

  approved_at timestamptz NULL,
  approved_by text NULL,

  paid_at timestamptz NULL,
  payment_reference text NULL,

  recovery_at timestamptz NULL,
  recovery_reference text NULL,

  closed_at timestamptz NULL,

  remarks text NULL,

  CONSTRAINT driver_settlement_batches_date_chk
    CHECK (from_date <= to_date),

  CONSTRAINT driver_settlement_batches_counts_chk
    CHECK (trip_count >= 0 AND advance_count >= 0),

  CONSTRAINT driver_settlement_batches_amounts_chk
    CHECK (
      driver_bata >= 0
      AND halt_bata >= 0
      AND trip_cash_advance >= 0
      AND direct_advance >= 0
    ),

  CONSTRAINT driver_settlement_batches_status_chk
    CHECK (
      settlement_status IN (
        'SETTLED',
        'PAID',
        'RECOVERY',
        'CLOSED',
        'REVERSED'
      )
    )
);


-- ============================================================
-- 2. SETTLEMENT LINES
-- ============================================================

CREATE TABLE IF NOT EXISTS public.driver_settlement_lines (
  settlement_line_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  settlement_id bigint NOT NULL
    REFERENCES public.driver_settlement_batches(settlement_id),

  line_type text NOT NULL,

  trip_id bigint NULL
    REFERENCES public.trips(trip_id),

  advance_id bigint NULL
    REFERENCES public.driver_direct_advances(advance_id),

  driver_id integer NOT NULL
    REFERENCES public.drivers(driver_id),

  transaction_date date NOT NULL,

  trip_number text NULL,

  driver_bata numeric NOT NULL DEFAULT 0,
  halt_bata numeric NOT NULL DEFAULT 0,
  trip_cash_advance numeric NOT NULL DEFAULT 0,

  direct_advance numeric NOT NULL DEFAULT 0,

  net_line_amount numeric NOT NULL DEFAULT 0,

  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT driver_settlement_lines_type_chk
    CHECK (line_type IN ('TRIP', 'DIRECT_ADVANCE')),

  CONSTRAINT driver_settlement_lines_source_chk
    CHECK (
      (line_type = 'TRIP'
        AND trip_id IS NOT NULL
        AND advance_id IS NULL)
      OR
      (line_type = 'DIRECT_ADVANCE'
        AND advance_id IS NOT NULL
        AND trip_id IS NULL)
    ),

  CONSTRAINT driver_settlement_lines_amounts_chk
    CHECK (
      driver_bata >= 0
      AND halt_bata >= 0
      AND trip_cash_advance >= 0
      AND direct_advance >= 0
    )
);


-- One source transaction can belong to only one settlement.
CREATE UNIQUE INDEX IF NOT EXISTS driver_settlement_lines_trip_unique
ON public.driver_settlement_lines(trip_id)
WHERE trip_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS driver_settlement_lines_advance_unique
ON public.driver_settlement_lines(advance_id)
WHERE advance_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS driver_settlement_lines_settlement_idx
ON public.driver_settlement_lines(settlement_id);


-- ============================================================
-- 3. DIRECT LINKS FROM SOURCE RECORDS
-- ============================================================

ALTER TABLE public.trips
  ADD COLUMN IF NOT EXISTS settlement_id bigint;

ALTER TABLE public.driver_direct_advances
  ADD COLUMN IF NOT EXISTS settlement_id bigint;


DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'trips_settlement_id_fkey'
  ) THEN
    ALTER TABLE public.trips
      ADD CONSTRAINT trips_settlement_id_fkey
      FOREIGN KEY (settlement_id)
      REFERENCES public.driver_settlement_batches(settlement_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'driver_direct_advances_settlement_id_fkey'
  ) THEN
    ALTER TABLE public.driver_direct_advances
      ADD CONSTRAINT driver_direct_advances_settlement_id_fkey
      FOREIGN KEY (settlement_id)
      REFERENCES public.driver_settlement_batches(settlement_id);
  END IF;
END $$;


CREATE INDEX IF NOT EXISTS trips_settlement_id_idx
ON public.trips(settlement_id);

CREATE INDEX IF NOT EXISTS driver_direct_advances_settlement_id_idx
ON public.driver_direct_advances(settlement_id);


-- ============================================================
-- 4. IMMUTABLE SETTLEMENT LINK PROTECTION
-- ============================================================

CREATE OR REPLACE FUNCTION public.protect_settlement_links()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'pg_catalog, public'
AS $function$
BEGIN

  IF TG_TABLE_NAME = 'trips' THEN

    IF OLD.settlement_id IS NOT NULL
       AND NEW.settlement_id IS DISTINCT FROM OLD.settlement_id THEN
      RAISE EXCEPTION
        'SETTLEMENT_LINK_IMMUTABLE: settled trip cannot be moved to another settlement';
    END IF;

    IF OLD.settlement_id IS NOT NULL
       AND TG_OP = 'DELETE' THEN
      RAISE EXCEPTION
        'SETTLEMENT_LINK_IMMUTABLE: settled trip cannot be deleted';
    END IF;

  ELSIF TG_TABLE_NAME = 'driver_direct_advances' THEN

    IF OLD.settlement_id IS NOT NULL
       AND NEW.settlement_id IS DISTINCT FROM OLD.settlement_id THEN
      RAISE EXCEPTION
        'SETTLEMENT_LINK_IMMUTABLE: settled advance cannot be moved to another settlement';
    END IF;

    IF OLD.settlement_id IS NOT NULL
       AND TG_OP = 'DELETE' THEN
      RAISE EXCEPTION
        'SETTLEMENT_LINK_IMMUTABLE: settled advance cannot be deleted';
    END IF;

  END IF;

  RETURN NEW;
END;
$function$;


DROP TRIGGER IF EXISTS trg_protect_trip_settlement_link
ON public.trips;

CREATE TRIGGER trg_protect_trip_settlement_link
BEFORE UPDATE OR DELETE
ON public.trips
FOR EACH ROW
EXECUTE FUNCTION public.protect_settlement_links();


DROP TRIGGER IF EXISTS trg_protect_driver_advance_settlement_link
ON public.driver_direct_advances;

CREATE TRIGGER trg_protect_driver_advance_settlement_link
BEFORE UPDATE OR DELETE
ON public.driver_direct_advances
FOR EACH ROW
EXECUTE FUNCTION public.protect_settlement_links();


-- ============================================================
-- 5. IMMUTABLE SETTLEMENT HEADER / LINES
-- ============================================================

CREATE OR REPLACE FUNCTION public.protect_driver_settlement_document()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'pg_catalog, public'
AS $function$
BEGIN

  IF TG_TABLE_NAME = 'driver_settlement_batches' THEN

    IF TG_OP = 'DELETE' THEN
      RAISE EXCEPTION
        'SETTLEMENT_DOCUMENT_IMMUTABLE: settlement documents cannot be deleted';
    END IF;

    IF OLD.driver_id IS DISTINCT FROM NEW.driver_id
       OR OLD.from_date IS DISTINCT FROM NEW.from_date
       OR OLD.to_date IS DISTINCT FROM NEW.to_date
       OR OLD.trip_count IS DISTINCT FROM NEW.trip_count
       OR OLD.advance_count IS DISTINCT FROM NEW.advance_count
       OR OLD.driver_bata IS DISTINCT FROM NEW.driver_bata
       OR OLD.halt_bata IS DISTINCT FROM NEW.halt_bata
       OR OLD.trip_cash_advance IS DISTINCT FROM NEW.trip_cash_advance
       OR OLD.direct_advance IS DISTINCT FROM NEW.direct_advance
       OR OLD.net_balance IS DISTINCT FROM NEW.net_balance
       OR OLD.settlement_number IS DISTINCT FROM NEW.settlement_number THEN

      RAISE EXCEPTION
        'SETTLEMENT_DOCUMENT_IMMUTABLE: historical settlement values cannot be changed';
    END IF;

    RETURN NEW;
  END IF;


  IF TG_TABLE_NAME = 'driver_settlement_lines' THEN

    IF TG_OP = 'DELETE' THEN
      RAISE EXCEPTION
        'SETTLEMENT_LINE_IMMUTABLE: settlement lines cannot be deleted';
    END IF;

    IF OLD.settlement_id IS DISTINCT FROM NEW.settlement_id
       OR OLD.line_type IS DISTINCT FROM NEW.line_type
       OR OLD.trip_id IS DISTINCT FROM NEW.trip_id
       OR OLD.advance_id IS DISTINCT FROM NEW.advance_id
       OR OLD.driver_id IS DISTINCT FROM NEW.driver_id
       OR OLD.transaction_date IS DISTINCT FROM NEW.transaction_date
       OR OLD.trip_number IS DISTINCT FROM NEW.trip_number
       OR OLD.driver_bata IS DISTINCT FROM NEW.driver_bata
       OR OLD.halt_bata IS DISTINCT FROM NEW.halt_bata
       OR OLD.trip_cash_advance IS DISTINCT FROM NEW.trip_cash_advance
       OR OLD.direct_advance IS DISTINCT FROM NEW.direct_advance
       OR OLD.net_line_amount IS DISTINCT FROM NEW.net_line_amount THEN

      RAISE EXCEPTION
        'SETTLEMENT_LINE_IMMUTABLE: historical settlement line cannot be changed';
    END IF;

    RETURN NEW;
  END IF;

  RETURN NEW;
END;
$function$;


DROP TRIGGER IF EXISTS trg_protect_driver_settlement_document
ON public.driver_settlement_batches;

CREATE TRIGGER trg_protect_driver_settlement_document
BEFORE UPDATE OR DELETE
ON public.driver_settlement_batches
FOR EACH ROW
EXECUTE FUNCTION public.protect_driver_settlement_document();


DROP TRIGGER IF EXISTS trg_protect_driver_settlement_line
ON public.driver_settlement_lines;

CREATE TRIGGER trg_protect_driver_settlement_line
BEFORE UPDATE OR DELETE
ON public.driver_settlement_lines
FOR EACH ROW
EXECUTE FUNCTION public.protect_driver_settlement_document();


-- ============================================================
-- 6. AUTHORITATIVE SETTLEMENT RPC
-- ============================================================

CREATE OR REPLACE FUNCTION public.settle_driver_period_atomic(
  p_driver_id integer,
  p_from_date date,
  p_to_date date
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'pg_catalog, public'
AS $function$
DECLARE
  v_role text;

  v_settlement_id bigint;
  v_settlement_number text;

  v_trip_count integer := 0;
  v_advance_count integer := 0;

  v_bata numeric := 0;
  v_halt_bata numeric := 0;
  v_trip_cash_advance numeric := 0;
  v_direct_advance numeric := 0;
  v_net_balance numeric := 0;

  v_now timestamptz := CURRENT_TIMESTAMP;
  v_created_by text := NULL;
BEGIN

  -- ----------------------------------------------------------
  -- Authorization
  -- ----------------------------------------------------------

  IF auth.role() <> 'service_role' THEN
    v_role := public.get_current_user_role();

    IF v_role NOT IN ('ADMIN', 'SUPERADMIN') THEN
      RAISE EXCEPTION
        'DRIVER_SETTLEMENT authorization requires ADMIN or SUPERADMIN';
    END IF;
  END IF;


  -- ----------------------------------------------------------
  -- Validation
  -- ----------------------------------------------------------

  IF p_driver_id IS NULL OR p_driver_id <= 0 THEN
    RAISE EXCEPTION 'Invalid driver ID';
  END IF;

  IF p_from_date IS NULL OR p_to_date IS NULL THEN
    RAISE EXCEPTION 'Settlement dates are required';
  END IF;

  IF p_from_date > p_to_date THEN
    RAISE EXCEPTION 'From date cannot be after to date';
  END IF;


  SELECT COALESCE(full_name, driver_code, 'SYSTEM')
  INTO v_created_by
  FROM public.app_users
  WHERE auth_user_id = auth.uid()
  LIMIT 1;


  -- ----------------------------------------------------------
  -- Driver validation
  -- ----------------------------------------------------------

  PERFORM 1
  FROM public.drivers
  WHERE driver_id = p_driver_id
    AND is_active = true;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Driver does not exist or is inactive';
  END IF;


  -- ----------------------------------------------------------
  -- Lock eligible trips.
  --
  -- POD is deliberately NOT checked.
  -- ----------------------------------------------------------

  PERFORM 1
  FROM public.trips
  WHERE primary_driver_id = p_driver_id
    AND trip_start_date BETWEEN p_from_date AND p_to_date
    AND trip_status = 'COMPLETED'
    AND COALESCE(settlement_status, 'UNSETTLED') <> 'SETTLED'
    AND settlement_id IS NULL
  FOR UPDATE;


  -- ----------------------------------------------------------
  -- Lock eligible direct advances.
  -- ----------------------------------------------------------

  PERFORM 1
  FROM public.driver_direct_advances
  WHERE driver_id = p_driver_id
    AND advance_date BETWEEN p_from_date AND p_to_date
    AND COALESCE(is_settled, false) = false
    AND settlement_id IS NULL
  FOR UPDATE;


  -- ----------------------------------------------------------
  -- Calculate authoritative totals.
  -- ----------------------------------------------------------

  SELECT
    COALESCE(SUM(COALESCE(driver_bata, 0)), 0),
    COALESCE(SUM(COALESCE(halt_bata, 0)), 0),
    COALESCE(SUM(COALESCE(cash_advance_issued, 0)), 0),
    COUNT(*)
  INTO
    v_bata,
    v_halt_bata,
    v_trip_cash_advance,
    v_trip_count
  FROM public.trips
  WHERE primary_driver_id = p_driver_id
    AND trip_start_date BETWEEN p_from_date AND p_to_date
    AND trip_status = 'COMPLETED'
    AND COALESCE(settlement_status, 'UNSETTLED') <> 'SETTLED'
    AND settlement_id IS NULL;


  SELECT
    COALESCE(SUM(COALESCE(amount_inr, 0)), 0),
    COUNT(*)
  INTO
    v_direct_advance,
    v_advance_count
  FROM public.driver_direct_advances
  WHERE driver_id = p_driver_id
    AND advance_date BETWEEN p_from_date AND p_to_date
    AND COALESCE(is_settled, false) = false
    AND settlement_id IS NULL;


  v_net_balance :=
      v_bata
    + v_halt_bata
    - v_trip_cash_advance
    - v_direct_advance;


  IF v_trip_count = 0 AND v_advance_count = 0 THEN
    RAISE EXCEPTION 'NOTHING_TO_SETTLE';
  END IF;


  -- ----------------------------------------------------------
  -- Create permanent settlement document.
  -- ----------------------------------------------------------

  v_settlement_number :=
    'KSS-DS-' ||
    LPAD(
      NEXTVAL('public.driver_settlement_number_seq')::text,
      8,
      '0'
    );


  INSERT INTO public.driver_settlement_batches (
    settlement_number,
    driver_id,
    from_date,
    to_date,
    trip_count,
    advance_count,
    driver_bata,
    halt_bata,
    trip_cash_advance,
    direct_advance,
    net_balance,
    settlement_status,
    created_at,
    created_by
  )
  VALUES (
    v_settlement_number,
    p_driver_id,
    p_from_date,
    p_to_date,
    v_trip_count,
    v_advance_count,
    v_bata,
    v_halt_bata,
    v_trip_cash_advance,
    v_direct_advance,
    v_net_balance,
    'SETTLED',
    v_now,
    v_created_by
  )
  RETURNING settlement_id
  INTO v_settlement_id;


  -- ----------------------------------------------------------
  -- Snapshot trip lines.
  -- ----------------------------------------------------------

  INSERT INTO public.driver_settlement_lines (
    settlement_id,
    line_type,
    trip_id,
    driver_id,
    transaction_date,
    trip_number,
    driver_bata,
    halt_bata,
    trip_cash_advance,
    direct_advance,
    net_line_amount
  )
  SELECT
    v_settlement_id,
    'TRIP',
    t.trip_id,
    t.primary_driver_id,
    t.trip_start_date,
    t.trip_number,
    COALESCE(t.driver_bata, 0),
    COALESCE(t.halt_bata, 0),
    COALESCE(t.cash_advance_issued, 0),
    0,
    COALESCE(t.driver_bata, 0)
      + COALESCE(t.halt_bata, 0)
      - COALESCE(t.cash_advance_issued, 0)
  FROM public.trips t
  WHERE t.primary_driver_id = p_driver_id
    AND t.trip_start_date BETWEEN p_from_date AND p_to_date
    AND t.trip_status = 'COMPLETED'
    AND COALESCE(t.settlement_status, 'UNSETTLED') <> 'SETTLED'
    AND t.settlement_id IS NULL;


  -- ----------------------------------------------------------
  -- Snapshot direct advance lines.
  -- ----------------------------------------------------------

  INSERT INTO public.driver_settlement_lines (
    settlement_id,
    line_type,
    advance_id,
    driver_id,
    transaction_date,
    trip_number,
    driver_bata,
    halt_bata,
    trip_cash_advance,
    direct_advance,
    net_line_amount
  )
  SELECT
    v_settlement_id,
    'DIRECT_ADVANCE',
    a.advance_id,
    a.driver_id,
    a.advance_date,
    NULL,
    0,
    0,
    0,
    COALESCE(a.amount_inr, 0),
    -COALESCE(a.amount_inr, 0)
  FROM public.driver_direct_advances a
  WHERE a.driver_id = p_driver_id
    AND a.advance_date BETWEEN p_from_date AND p_to_date
    AND COALESCE(a.is_settled, false) = false
    AND a.settlement_id IS NULL;


  -- ----------------------------------------------------------
  -- Link and settle exactly the snapshotted records.
  -- ----------------------------------------------------------

  UPDATE public.trips t
  SET
    settlement_id = v_settlement_id,
    settlement_status = 'SETTLED',
    settled_at = v_now
  WHERE t.trip_id IN (
    SELECT l.trip_id
    FROM public.driver_settlement_lines l
    WHERE l.settlement_id = v_settlement_id
      AND l.line_type = 'TRIP'
  );


  UPDATE public.driver_direct_advances a
  SET
    settlement_id = v_settlement_id,
    is_settled = true,
    settled_at = v_now
  WHERE a.advance_id IN (
    SELECT l.advance_id
    FROM public.driver_settlement_lines l
    WHERE l.settlement_id = v_settlement_id
      AND l.line_type = 'DIRECT_ADVANCE'
  );


  -- ----------------------------------------------------------
  -- Return authoritative settlement document.
  -- ----------------------------------------------------------

  RETURN jsonb_build_object(
    'success', true,

    'settlement_id', v_settlement_id,
    'settlement_number', v_settlement_number,

    'driver_id', p_driver_id,
    'from_date', p_from_date,
    'to_date', p_to_date,

    'trips_settled', v_trip_count,
    'advances_settled', v_advance_count,

    'driver_bata', v_bata,
    'halt_bata', v_halt_bata,
    'trip_cash_advance', v_trip_cash_advance,
    'direct_advance', v_direct_advance,

    'net_balance', v_net_balance,

    'settlement_status', 'SETTLED',
    'settled_at', v_now
  );
END;
$function$;


-- ============================================================
-- 7. SETTLEMENT DOCUMENT ACL
-- ============================================================

REVOKE ALL
ON TABLE public.driver_settlement_batches
FROM PUBLIC, anon, authenticated;

REVOKE ALL
ON TABLE public.driver_settlement_lines
FROM PUBLIC, anon, authenticated;

GRANT SELECT
ON TABLE public.driver_settlement_batches,
           public.driver_settlement_lines
TO authenticated;

GRANT ALL
ON TABLE public.driver_settlement_batches,
           public.driver_settlement_lines
TO service_role;


REVOKE EXECUTE
ON FUNCTION public.settle_driver_period_atomic(integer, date, date)
FROM PUBLIC, anon;

GRANT EXECUTE
ON FUNCTION public.settle_driver_period_atomic(integer, date, date)
TO authenticated, service_role;


-- ============================================================
-- 8. SEQUENCE ACCESS
-- ============================================================

REVOKE ALL
ON SEQUENCE public.driver_settlement_number_seq
FROM PUBLIC, anon, authenticated;

GRANT USAGE, SELECT
ON SEQUENCE public.driver_settlement_number_seq
TO service_role;


COMMIT;
