-- KSS ERP: Spare Parts Inventory
-- P4.5
--
-- Design:
--   inventory_items
--   inventory_purchase_bills
--   inventory_purchase_items
--   inventory_stock_movements
--
-- Stock is derived from immutable stock movements.
-- Purchase receipt + payable creation is atomic.
-- Direct client writes are blocked; mutations go through SECURITY DEFINER RPCs.

-- ============================================================================
-- 1. ITEM MASTER
-- ============================================================================

create table if not exists public.inventory_items (
  item_id bigint generated by default as identity primary key,
  item_code text not null,
  item_name text not null,
  category text not null default 'GENERAL',
  unit text not null default 'PCS',
  minimum_stock numeric(14,3) not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint inventory_items_code_chk
    check (btrim(item_code) <> ''),

  constraint inventory_items_name_chk
    check (btrim(item_name) <> ''),

  constraint inventory_items_minimum_stock_chk
    check (minimum_stock >= 0),

  constraint inventory_items_unit_chk
    check (upper(btrim(unit)) in ('PCS','NOS','SET','LTR','KG','BOX'))
);

create unique index if not exists inventory_items_code_uidx
  on public.inventory_items (upper(btrim(item_code)));

create index if not exists inventory_items_category_idx
  on public.inventory_items (category);

create index if not exists inventory_items_active_idx
  on public.inventory_items (is_active);


-- ============================================================================
-- 2. PURCHASE BILL HEADER
-- ============================================================================

create table if not exists public.inventory_purchase_bills (
  purchase_bill_id bigint generated by default as identity primary key,
  bill_date date not null default current_date,
  invoice_date date,
  invoice_number text,
  vendor_id integer not null,
  payable_id bigint,
  payment_status text not null default 'CREDIT',
  subtotal_amount numeric(14,2) not null default 0,
  tax_amount numeric(14,2) not null default 0,
  total_bill_amount numeric(14,2) not null default 0,
  remarks text,
  created_by text,
  created_at timestamptz not null default now(),

  constraint inventory_purchase_bills_amount_chk
    check (
      subtotal_amount >= 0
      and tax_amount >= 0
      and total_bill_amount >= 0
    ),

  constraint inventory_purchase_bills_payment_status_chk
    check (
      upper(btrim(payment_status))
      in ('PAID','CREDIT','PARTIAL','CANCELLED')
    ),

  constraint inventory_purchase_bills_vendor_fk
    foreign key (vendor_id)
    references public.vendors(vendor_id),

  constraint inventory_purchase_bills_payable_fk
    foreign key (payable_id)
    references public.vendor_payables(payable_id)
);

create index if not exists inventory_purchase_bills_vendor_idx
  on public.inventory_purchase_bills (vendor_id);

create index if not exists inventory_purchase_bills_date_idx
  on public.inventory_purchase_bills (bill_date desc);

create index if not exists inventory_purchase_bills_payable_idx
  on public.inventory_purchase_bills (payable_id);


-- ============================================================================
-- 3. PURCHASE BILL ITEMS
-- ============================================================================

create table if not exists public.inventory_purchase_items (
  purchase_item_id bigint generated by default as identity primary key,
  purchase_bill_id bigint not null,
  item_id bigint not null,
  quantity numeric(14,3) not null,
  unit_amount numeric(14,2) not null,
  line_amount numeric(14,2) generated always as
    (round(quantity * unit_amount, 2)) stored,
  created_at timestamptz not null default now(),

  constraint inventory_purchase_items_qty_chk
    check (quantity > 0),

  constraint inventory_purchase_items_unit_amount_chk
    check (unit_amount >= 0),

  constraint inventory_purchase_items_bill_fk
    foreign key (purchase_bill_id)
    references public.inventory_purchase_bills(purchase_bill_id)
    on delete cascade,

  constraint inventory_purchase_items_item_fk
    foreign key (item_id)
    references public.inventory_items(item_id)
);

create index if not exists inventory_purchase_items_bill_idx
  on public.inventory_purchase_items (purchase_bill_id);

create index if not exists inventory_purchase_items_item_idx
  on public.inventory_purchase_items (item_id);


-- ============================================================================
-- 4. IMMUTABLE STOCK MOVEMENT LEDGER
-- ============================================================================

create table if not exists public.inventory_stock_movements (
  movement_id bigint generated by default as identity primary key,
  item_id bigint not null,
  movement_type text not null,
  quantity numeric(14,3) not null,
  reference_type text,
  reference_id bigint,
  vehicle_id integer,
  reason text,
  created_by text,
  created_at timestamptz not null default now(),

  constraint inventory_stock_movements_type_chk
    check (
      upper(btrim(movement_type))
      in (
        'OPENING',
        'PURCHASE_RECEIPT',
        'ISSUE',
        'RETURN',
        'ADJUSTMENT_IN',
        'ADJUSTMENT_OUT',
        'REVERSAL'
      )
    ),

  constraint inventory_stock_movements_qty_chk
    check (quantity > 0),

  constraint inventory_stock_movements_item_fk
    foreign key (item_id)
    references public.inventory_items(item_id),

  constraint inventory_stock_movements_vehicle_fk
    foreign key (vehicle_id)
    references public.vehicles(vehicle_id)
);

create index if not exists inventory_stock_movements_item_date_idx
  on public.inventory_stock_movements (item_id, created_at desc);

create index if not exists inventory_stock_movements_reference_idx
  on public.inventory_stock_movements (reference_type, reference_id);

create index if not exists inventory_stock_movements_vehicle_idx
  on public.inventory_stock_movements (vehicle_id);


-- ============================================================================
-- 5. STOCK BALANCE VIEW
-- ============================================================================

create or replace view public.inventory_stock_balance
with (security_invoker = true)
as
select
  i.item_id,
  i.item_code,
  i.item_name,
  i.category,
  i.unit,
  i.minimum_stock,
  i.is_active,
  coalesce(
    sum(
      case
        when m.movement_type in (
          'OPENING',
          'PURCHASE_RECEIPT',
          'RETURN',
          'ADJUSTMENT_IN'
        ) then m.quantity
        when m.movement_type in (
          'ISSUE',
          'ADJUSTMENT_OUT',
          'REVERSAL'
        ) then -m.quantity
        else 0
      end
    ),
    0
  )::numeric(14,3) as current_stock
from public.inventory_items i
left join public.inventory_stock_movements m
  on m.item_id = i.item_id
group by
  i.item_id,
  i.item_code,
  i.item_name,
  i.category,
  i.unit,
  i.minimum_stock,
  i.is_active;


-- ============================================================================
-- 6. ITEM MASTER RPC
-- ============================================================================

create or replace function public.create_inventory_item(
  p_item_code text,
  p_item_name text,
  p_category text default 'GENERAL',
  p_unit text default 'PCS',
  p_minimum_stock numeric default 0
)
returns public.inventory_items
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_row public.inventory_items%rowtype;
begin
  if not public.is_current_user_superadmin() then
    raise exception 'SUPERADMIN authorization required';
  end if;

  if p_item_code is null or btrim(p_item_code) = '' then
    raise exception 'Item code is required';
  end if;

  if p_item_name is null or btrim(p_item_name) = '' then
    raise exception 'Item name is required';
  end if;

  if coalesce(p_minimum_stock, 0) < 0 then
    raise exception 'Minimum stock cannot be negative';
  end if;

  if upper(btrim(coalesce(p_unit, 'PCS')))
     not in ('PCS','NOS','SET','LTR','KG','BOX') then
    raise exception 'Invalid inventory unit';
  end if;

  insert into public.inventory_items (
    item_code,
    item_name,
    category,
    unit,
    minimum_stock
  )
  values (
    upper(btrim(p_item_code)),
    upper(btrim(p_item_name)),
    upper(btrim(coalesce(p_category, 'GENERAL'))),
    upper(btrim(coalesce(p_unit, 'PCS'))),
    coalesce(p_minimum_stock, 0)
  )
  returning * into v_row;

  return v_row;

exception
  when unique_violation then
    raise exception 'Inventory item code already exists';
end;
$$;

revoke all on function public.create_inventory_item(text,text,text,text,numeric)
from public;

grant execute on function public.create_inventory_item(text,text,text,text,numeric)
to authenticated;


-- ============================================================================
-- 7. PURCHASE + STOCK RECEIPT + PAYABLE ATOMIC RPC
-- ============================================================================

create or replace function public.create_inventory_purchase_atomic(
  p_vendor_id integer,
  p_bill_date date,
  p_invoice_number text default null,
  p_invoice_date date default null,
  p_subtotal_amount numeric default 0,
  p_tax_amount numeric default 0,
  p_total_bill_amount numeric default 0,
  p_payment_status text default 'CREDIT',
  p_remarks text default null,
  p_created_by text default null,
  p_items jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_bill public.inventory_purchase_bills%rowtype;
  v_payable public.vendor_payables%rowtype;
  v_item jsonb;
  v_item_id bigint;
  v_quantity numeric;
  v_unit_amount numeric;
  v_line_total numeric;
  v_computed_subtotal numeric := 0;
  v_item_count integer := 0;
  v_payment_status text;
begin
  if not public.is_current_user_superadmin() then
    raise exception 'SUPERADMIN authorization required';
  end if;

  if p_vendor_id is null then
    raise exception 'Vendor is required';
  end if;

  if not exists (
    select 1
    from public.vendors
    where vendor_id = p_vendor_id
      and is_active = true
  ) then
    raise exception 'Active vendor not found';
  end if;

  if p_bill_date is null then
    raise exception 'Bill date is required';
  end if;

  if p_subtotal_amount < 0
     or p_tax_amount < 0
     or p_total_bill_amount < 0 then
    raise exception 'Purchase amounts cannot be negative';
  end if;

  v_payment_status := upper(btrim(coalesce(p_payment_status, 'CREDIT')));

  if v_payment_status not in ('PAID','CREDIT','PARTIAL') then
    raise exception 'Invalid payment status';
  end if;

  if jsonb_typeof(p_items) <> 'array'
     or jsonb_array_length(p_items) = 0 then
    raise exception 'At least one purchase item is required';
  end if;

  -- Validate and calculate item totals before writing anything.
  for v_item in
    select value
    from jsonb_array_elements(p_items)
  loop
    v_item_id := nullif(v_item->>'item_id', '')::bigint;
    v_quantity := nullif(v_item->>'quantity', '')::numeric;
    v_unit_amount := nullif(v_item->>'unit_amount', '')::numeric;

    if v_item_id is null then
      raise exception 'Purchase item ID is required';
    end if;

    if not exists (
      select 1
      from public.inventory_items
      where item_id = v_item_id
        and is_active = true
    ) then
      raise exception 'Inventory item % not found or inactive', v_item_id;
    end if;

    if v_quantity is null or v_quantity <= 0 then
      raise exception 'Purchase quantity must be greater than zero';
    end if;

    if v_unit_amount is null or v_unit_amount < 0 then
      raise exception 'Purchase unit amount cannot be negative';
    end if;

    v_line_total := round(v_quantity * v_unit_amount, 2);
    v_computed_subtotal := v_computed_subtotal + v_line_total;
    v_item_count := v_item_count + 1;
  end loop;

  if abs(v_computed_subtotal - coalesce(p_subtotal_amount, 0)) > 0.01 then
    raise exception
      'Purchase subtotal mismatch: expected %, received %',
      v_computed_subtotal,
      p_subtotal_amount;
  end if;

  if abs(
    (
      coalesce(p_subtotal_amount, 0)
      + coalesce(p_tax_amount, 0)
    )
    - coalesce(p_total_bill_amount, 0)
  ) > 0.01 then
    raise exception 'Purchase total does not match subtotal plus tax';
  end if;

  -- Purchase header.
  insert into public.inventory_purchase_bills (
    bill_date,
    invoice_date,
    invoice_number,
    vendor_id,
    payment_status,
    subtotal_amount,
    tax_amount,
    total_bill_amount,
    remarks,
    created_by
  )
  values (
    p_bill_date,
    p_invoice_date,
    nullif(btrim(p_invoice_number), ''),
    p_vendor_id,
    v_payment_status,
    p_subtotal_amount,
    p_tax_amount,
    p_total_bill_amount,
    nullif(btrim(p_remarks), ''),
    nullif(btrim(p_created_by), '')
  )
  returning * into v_bill;

  -- Vendor payable for credit/partial purchases.
  if v_payment_status in ('CREDIT', 'PARTIAL') then
    insert into public.vendor_payables (
      vendor_id,
      bill_amount,
      bill_date,
      invoice_number,
      description,
      paid_amount,
      outstanding_amount,
      status,
      source_type,
      source_reference_id
    )
    values (
      p_vendor_id,
      p_total_bill_amount,
      p_bill_date,
      nullif(btrim(p_invoice_number), ''),
      'Spare parts inventory purchase',
      0,
      p_total_bill_amount,
      case when v_payment_status = 'PARTIAL'
           then 'PARTIAL'
           else 'UNPAID'
      end,
      'INVENTORY_PURCHASE',
      v_bill.purchase_bill_id
    )
    returning * into v_payable;

    update public.inventory_purchase_bills
    set payable_id = v_payable.payable_id
    where purchase_bill_id = v_bill.purchase_bill_id;
  end if;

  -- Purchase lines + stock receipt ledger.
  for v_item in
    select value
    from jsonb_array_elements(p_items)
  loop
    v_item_id := (v_item->>'item_id')::bigint;
    v_quantity := (v_item->>'quantity')::numeric;
    v_unit_amount := (v_item->>'unit_amount')::numeric;

    insert into public.inventory_purchase_items (
      purchase_bill_id,
      item_id,
      quantity,
      unit_amount
    )
    values (
      v_bill.purchase_bill_id,
      v_item_id,
      v_quantity,
      v_unit_amount
    );

    insert into public.inventory_stock_movements (
      item_id,
      movement_type,
      quantity,
      reference_type,
      reference_id,
      reason,
      created_by
    )
    values (
      v_item_id,
      'PURCHASE_RECEIPT',
      v_quantity,
      'INVENTORY_PURCHASE',
      v_bill.purchase_bill_id,
      'Purchase receipt',
      nullif(btrim(p_created_by), '')
    );
  end loop;

  return jsonb_build_object(
    'purchase_bill_id', v_bill.purchase_bill_id,
    'payable_id', v_payable.payable_id,
    'item_count', v_item_count,
    'subtotal_amount', p_subtotal_amount,
    'tax_amount', p_tax_amount,
    'total_bill_amount', p_total_bill_amount
  );
end;
$$;

revoke all on function public.create_inventory_purchase_atomic(
  integer,
  date,
  text,
  date,
  numeric,
  numeric,
  numeric,
  text,
  text,
  text,
  jsonb
) from public;

grant execute on function public.create_inventory_purchase_atomic(
  integer,
  date,
  text,
  date,
  numeric,
  numeric,
  numeric,
  text,
  text,
  text,
  jsonb
) to authenticated;


-- ============================================================================
-- 8. ISSUE STOCK
-- ============================================================================

create or replace function public.issue_inventory_stock(
  p_item_id bigint,
  p_quantity numeric,
  p_vehicle_id integer default null,
  p_reason text default null,
  p_created_by text default null
)
returns public.inventory_stock_movements
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_current numeric;
  v_row public.inventory_stock_movements%rowtype;
begin
  if not public.is_current_user_superadmin() then
    raise exception 'SUPERADMIN authorization required';
  end if;

  if p_quantity is null or p_quantity <= 0 then
    raise exception 'Issue quantity must be greater than zero';
  end if;

  if not exists (
    select 1
    from public.inventory_items
    where item_id = p_item_id
      and is_active = true
  ) then
    raise exception 'Inventory item not found or inactive';
  end if;

  if p_vehicle_id is not null and not exists (
    select 1
    from public.vehicles
    where vehicle_id = p_vehicle_id
  ) then
    raise exception 'Invalid vehicle';
  end if;

  select coalesce(sum(
    case
      when movement_type in (
        'OPENING',
        'PURCHASE_RECEIPT',
        'RETURN',
        'ADJUSTMENT_IN'
      ) then quantity
      when movement_type in (
        'ISSUE',
        'ADJUSTMENT_OUT',
        'REVERSAL'
      ) then -quantity
      else 0
    end
  ), 0)
  into v_current
  from public.inventory_stock_movements
  where item_id = p_item_id;

  if coalesce(v_current, 0) < p_quantity then
    raise exception
      'Insufficient stock. Available: %, requested: %',
      coalesce(v_current, 0),
      p_quantity;
  end if;

  insert into public.inventory_stock_movements (
    item_id,
    movement_type,
    quantity,
    reference_type,
    vehicle_id,
    reason,
    created_by
  )
  values (
    p_item_id,
    'ISSUE',
    p_quantity,
    'WORKSHOP_ISSUE',
    p_vehicle_id,
    nullif(btrim(p_reason), ''),
    nullif(btrim(p_created_by), '')
  )
  returning * into v_row;

  return v_row;
end;
$$;

revoke all on function public.issue_inventory_stock(
  bigint,
  numeric,
  integer,
  text,
  text
) from public;

grant execute on function public.issue_inventory_stock(
  bigint,
  numeric,
  integer,
  text,
  text
) to authenticated;


-- ============================================================================
-- 9. DIRECT TABLE WRITE PROTECTION
-- ============================================================================

revoke insert, update, delete, truncate, references, trigger
on public.inventory_items
from anon, authenticated;

revoke insert, update, delete, truncate, references, trigger
on public.inventory_purchase_bills
from anon, authenticated;

revoke insert, update, delete, truncate, references, trigger
on public.inventory_purchase_items
from anon, authenticated;

revoke insert, update, delete, truncate, references, trigger
on public.inventory_stock_movements
from anon, authenticated;

-- Read-only access for authenticated ERP users.
grant select on public.inventory_items
to authenticated;

grant select on public.inventory_purchase_bills
to authenticated;

grant select on public.inventory_purchase_items
to authenticated;

grant select on public.inventory_stock_movements
to authenticated;

grant select on public.inventory_stock_balance
to authenticated;


-- ============================================================================
-- 10. IMMUTABILITY TRIGGER FOR STOCK LEDGER
-- ============================================================================

create or replace function public.prevent_inventory_stock_movement_mutation()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  raise exception 'Inventory stock movements are immutable';
end;
$$;

drop trigger if exists trg_inventory_stock_movement_immutable
on public.inventory_stock_movements;

create trigger trg_inventory_stock_movement_immutable
before update or delete
on public.inventory_stock_movements
for each row
execute function public.prevent_inventory_stock_movement_mutation();


-- ============================================================================
-- 11. COMMENTS
-- ============================================================================

comment on table public.inventory_items is
  'Master list of workshop spare parts and consumable inventory items.';

comment on table public.inventory_purchase_bills is
  'Purchase invoices for spare-parts inventory.';

comment on table public.inventory_purchase_items is
  'Line items belonging to spare-parts purchase bills.';

comment on table public.inventory_stock_movements is
  'Immutable stock ledger. Current stock is derived from these movements.';

comment on view public.inventory_stock_balance is
  'Current calculated stock balance per inventory item.';
