-- KSS ERP: Customer Master
-- Secure SUPERADMIN-only master CRUD.

create table if not exists public.customers (
  customer_id bigint generated by default as identity primary key,
  customer_code text not null,
  customer_name text not null,
  customer_type text not null default 'CUSTOMER',
  contact_person text,
  phone_number text,
  email text,
  tax_number text,
  billing_address text,
  payment_terms text,
  credit_limit numeric(14,2) not null default 0,
  remarks text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists customers_code_uq
  on public.customers (lower(btrim(customer_code)));

create index if not exists customers_name_idx
  on public.customers (lower(customer_name));

create index if not exists customers_active_idx
  on public.customers (is_active);

alter table public.customers enable row level security;

drop policy if exists "customers_read_authenticated" on public.customers;

create policy "customers_read_authenticated"
on public.customers
for select
to authenticated
using (true);


create or replace function public.create_master_customer(
  p_customer_code text,
  p_customer_name text,
  p_customer_type text default 'CUSTOMER',
  p_contact_person text default null,
  p_phone_number text default null,
  p_email text default null,
  p_tax_number text default null,
  p_billing_address text default null,
  p_payment_terms text default null,
  p_credit_limit numeric default 0,
  p_remarks text default null
)
returns public.customers
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_customer public.customers%rowtype;
begin
  if not public.is_current_user_superadmin() then
    raise exception 'SUPERADMIN authorization required';
  end if;

  if p_customer_code is null or btrim(p_customer_code) = '' then
    raise exception 'Customer code is required';
  end if;

  if p_customer_name is null or btrim(p_customer_name) = '' then
    raise exception 'Customer name is required';
  end if;

  if coalesce(p_credit_limit, 0) < 0 then
    raise exception 'Credit limit cannot be negative';
  end if;

  if exists (
    select 1
    from public.customers
    where lower(btrim(customer_code)) = lower(btrim(p_customer_code))
  ) then
    raise exception 'Customer code already exists';
  end if;

  insert into public.customers (
    customer_code,
    customer_name,
    customer_type,
    contact_person,
    phone_number,
    email,
    tax_number,
    billing_address,
    payment_terms,
    credit_limit,
    remarks,
    is_active
  )
  values (
    upper(btrim(p_customer_code)),
    btrim(p_customer_name),
    coalesce(nullif(btrim(p_customer_type), ''), 'CUSTOMER'),
    nullif(btrim(p_contact_person), ''),
    nullif(btrim(p_phone_number), ''),
    nullif(btrim(p_email), ''),
    nullif(btrim(p_tax_number), ''),
    nullif(btrim(p_billing_address), ''),
    nullif(btrim(p_payment_terms), ''),
    coalesce(p_credit_limit, 0),
    nullif(btrim(p_remarks), ''),
    true
  )
  returning * into v_customer;

  return v_customer;
end;
$$;


create or replace function public.update_master_customer(
  p_customer_id bigint,
  p_customer_code text,
  p_customer_name text,
  p_customer_type text default 'CUSTOMER',
  p_contact_person text default null,
  p_phone_number text default null,
  p_email text default null,
  p_tax_number text default null,
  p_billing_address text default null,
  p_payment_terms text default null,
  p_credit_limit numeric default 0,
  p_remarks text default null,
  p_is_active boolean default true
)
returns public.customers
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_customer public.customers%rowtype;
begin
  if not public.is_current_user_superadmin() then
    raise exception 'SUPERADMIN authorization required';
  end if;

  if p_customer_id is null then
    raise exception 'Customer ID is required';
  end if;

  if p_customer_code is null or btrim(p_customer_code) = '' then
    raise exception 'Customer code is required';
  end if;

  if p_customer_name is null or btrim(p_customer_name) = '' then
    raise exception 'Customer name is required';
  end if;

  if coalesce(p_credit_limit, 0) < 0 then
    raise exception 'Credit limit cannot be negative';
  end if;

  if exists (
    select 1
    from public.customers
    where lower(btrim(customer_code)) = lower(btrim(p_customer_code))
      and customer_id <> p_customer_id
  ) then
    raise exception 'Customer code already exists';
  end if;

  update public.customers
  set
    customer_code = upper(btrim(p_customer_code)),
    customer_name = btrim(p_customer_name),
    customer_type = coalesce(nullif(btrim(p_customer_type), ''), 'CUSTOMER'),
    contact_person = nullif(btrim(p_contact_person), ''),
    phone_number = nullif(btrim(p_phone_number), ''),
    email = nullif(btrim(p_email), ''),
    tax_number = nullif(btrim(p_tax_number), ''),
    billing_address = nullif(btrim(p_billing_address), ''),
    payment_terms = nullif(btrim(p_payment_terms), ''),
    credit_limit = coalesce(p_credit_limit, 0),
    remarks = nullif(btrim(p_remarks), ''),
    is_active = coalesce(p_is_active, true)
  where customer_id = p_customer_id
  returning * into v_customer;

  if not found then
    raise exception 'Customer not found';
  end if;

  return v_customer;
end;
$$;


revoke all on function public.create_master_customer(
  text, text, text, text, text, text, text, text, text, numeric, text
) from public, anon;

grant execute on function public.create_master_customer(
  text, text, text, text, text, text, text, text, text, numeric, text
) to authenticated, service_role;


revoke all on function public.update_master_customer(
  bigint, text, text, text, text, text, text, text, text, text, numeric, text, boolean
) from public, anon;

grant execute on function public.update_master_customer(
  bigint, text, text, text, text, text, text, text, text, text, numeric, text, boolean
) to authenticated, service_role;


revoke all on table public.customers from anon;

grant select on table public.customers to authenticated, service_role;
grant usage, select on sequence public.customers_customer_id_seq to authenticated, service_role;
